using System.Diagnostics;
using System.Text;

namespace Plus.CodeStyle;

internal static class Program
{
    private static async Task<int> Main(string[] args)
    {
        if (args.Length != 1 || args[0] is not ("fix" or "check"))
        {
            Console.Error.WriteLine("Usage: dotnet run --project tools/Plus.CodeStyle -- fix|check (from the repository root)");

            return 2;
        }

        const string solution = "Plus Emulator.sln";

        if (!File.Exists(solution))
        {
            Console.Error.WriteLine("Run this command from the repository root.");

            return 2;
        }

        bool check = args[0] == "check";
        int result = 0;

        foreach (string category in new[] { "style", "whitespace" })
        {
            var start = new ProcessStartInfo("dotnet") { UseShellExecute = false };

            foreach (string argument in new[] { "format", category, solution, "--verbosity", "minimal" })
            {
                start.ArgumentList.Add(argument);
            }

            if (category == "style")
            {
                start.ArgumentList.Add("--diagnostics");
                start.ArgumentList.Add("IDE0011");
            }

            if (check)
            {
                start.ArgumentList.Add("--verify-no-changes");
            }

            using var process = Process.Start(start)!;
            await process.WaitForExitAsync();

            if (process.ExitCode != 0)
            {
                result = 1;

                if (!check)
                {
                    return result;
                }
            }
        }

        int changed = 0;

        foreach (string path in SourceFiles(Directory.GetCurrentDirectory()).Order(StringComparer.Ordinal))
        {
            string source = await File.ReadAllTextAsync(path);
            string formatted;

            try
            {
                formatted = StatementSpacing.Format(source);
            }
            catch (InvalidDataException error)
            {
                Console.Error.WriteLine($"{Path.GetRelativePath(Directory.GetCurrentDirectory(), path)}: {error.Message}");
                result = 1;
                continue;
            }

            if (source == formatted)
            {
                continue;
            }

            changed++;
            Console.WriteLine($"{(check ? "Needs blank lines" : "Formatted")}: {Path.GetRelativePath(Directory.GetCurrentDirectory(), path)}");

            if (!check)
            {
                await File.WriteAllTextAsync(path, formatted, new UTF8Encoding(false));
            }
        }

        Console.WriteLine(check ? $"Blank-line check: {changed} files need formatting." : $"Added blank lines in {changed} files.");

        return result != 0 || (check && changed != 0) ? 1 : 0;
    }

    private static IEnumerable<string> SourceFiles(string directory)
    {
        foreach (string path in Directory.EnumerateFiles(directory, "*.cs"))
        {
            if (!path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
                && !path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
                && !File.ReadLines(path).Take(5).Any(line => line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)))
            {
                yield return path;
            }
        }

        foreach (string child in Directory.EnumerateDirectories(directory))
        {
            if (Path.GetFileName(child) is ".git" or "bin" or "obj"
                || (File.GetAttributes(child) & FileAttributes.ReparsePoint) != 0)
            {
                continue;
            }

            foreach (string path in SourceFiles(child))
            {
                yield return path;
            }
        }
    }
}
