using System.Collections.Frozen;

namespace Plus.HabboHotel.Items.Wired.Configuration;

/// <summary>
/// EditorCode is the native AIR form code within the box's own category (Action/Trigger/Condition/Selector/Addon/Variable
/// code spaces are independent); behavioral registration
/// remains the concrete factory's responsibility. Octane uses three legacy envelopes for six kinds.
/// </summary>
public static class WiredBoxRegistry
{
    private static readonly FrozenDictionary<string, WiredBoxDescriptor> Descriptors = new WiredBoxDescriptor[]
    {
        new("wf_act_give_currency", WiredBoxCategory.Action, 45, "Turbo f702041c/WiredTrading"),
        new("wf_act_give_furni", WiredBoxCategory.Action, 46, "Turbo f702041c/WiredTrading"),
        new("wf_act_init_transaction", WiredBoxCategory.Action, 47, "Turbo f702041c/WiredTrading"),
        new("wf_act_cancel_transaction", WiredBoxCategory.Action, 48, "Turbo f702041c/WiredTrading"),
        new("wf_cnd_chest_has_items", WiredBoxCategory.Condition, 45, "Turbo f702041c/WiredTrading"),
        new("wf_cnd_chest_has_item_type", WiredBoxCategory.Condition, 46, "Turbo f702041c/WiredTrading"),
        new("wf_trg_transaction_complete", WiredBoxCategory.Trigger, 25, "Turbo f702041c/WiredTrading"),
        new("wf_trg_transaction_fail", WiredBoxCategory.Trigger, 26, "Turbo f702041c/WiredTrading"),
        new("wf_xtra_scan_chest_furni_by_type", WiredBoxCategory.Addon, 18, "Turbo f702041c/WiredTrading"),
        new("wf_xtra_custom_contract", WiredBoxCategory.Addon, 20, "Turbo f702041c/WiredTrading"),
        new("wf_act_adjust_clock", WiredBoxCategory.Action, 38, "habbohotel/items/interactions/wired/effects/WiredEffectAdjustClock.java"),
        new("wf_act_bot_clothes", WiredBoxCategory.Action, 26, "habbohotel/items/interactions/wired/effects/WiredEffectBotClothes.java"),
        new("wf_act_bot_follow_avatar", WiredBoxCategory.Action, 25, "habbohotel/items/interactions/wired/effects/WiredEffectBotFollowHabbo.java"),
        new("wf_act_bot_give_handitem", WiredBoxCategory.Action, 24, "habbohotel/items/interactions/wired/effects/WiredEffectBotGiveHandItem.java"),
        new("wf_act_bot_move", WiredBoxCategory.Action, 22, "habbohotel/items/interactions/wired/effects/WiredEffectBotWalkToFurni.java"),
        new("wf_act_bot_talk", WiredBoxCategory.Action, 23, "habbohotel/items/interactions/wired/effects/WiredEffectBotTalk.java"),
        new("wf_act_bot_talk_to_avatar", WiredBoxCategory.Action, 27, "habbohotel/items/interactions/wired/effects/WiredEffectBotTalkToHabbo.java"),
        new("wf_act_bot_teleport", WiredBoxCategory.Action, 21, "habbohotel/items/interactions/wired/effects/WiredEffectBotTeleport.java"),
        new("wf_act_call_stacks", WiredBoxCategory.Action, 18, "habbohotel/items/interactions/wired/effects/WiredEffectTriggerStacks.java"),
        new("wf_act_change_var_val", WiredBoxCategory.Action, 41, "habbohotel/items/interactions/wired/effects/WiredEffectChangeVariableValue.java"),
        new("wf_act_chase", WiredBoxCategory.Action, 11, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniTowards.java"),
        new("wf_act_click_conf", WiredBoxCategory.Action, 54, "habbohotel/items/interactions/wired/effects/WiredEffectClickSettings.java"),
        new("wf_act_control_clock", WiredBoxCategory.Action, 28, "habbohotel/items/interactions/wired/effects/WiredEffectControlClock.java"),
        new("wf_act_flee", WiredBoxCategory.Action, 12, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniAway.java"),
        new("wf_act_freeze", WiredBoxCategory.Action, 31, "habbohotel/items/interactions/wired/effects/WiredEffectFreeze.java"),
        new("wf_act_furni_to_furni", WiredBoxCategory.Action, 34, "habbohotel/items/interactions/wired/effects/WiredEffectFurniToFurni.java"),
        new("wf_act_furni_to_user", WiredBoxCategory.Action, 35, "habbohotel/items/interactions/wired/effects/WiredEffectFurniToUser.java"),
        new("wf_act_give_reward", WiredBoxCategory.Action, 17, "habbohotel/items/interactions/wired/effects/WiredEffectGiveReward.java"),
        new("wf_act_give_score", WiredBoxCategory.Action, 6, "habbohotel/items/interactions/wired/effects/WiredEffectGiveScore.java"),
        new("wf_act_give_score_tm", WiredBoxCategory.Action, 14, "habbohotel/items/interactions/wired/effects/WiredEffectGiveScoreToTeam.java"),
        new("wf_act_give_var", WiredBoxCategory.Action, 39, "habbohotel/items/interactions/wired/effects/WiredEffectGiveVariable.java"),
        new("wf_act_join_team", WiredBoxCategory.Action, 9, "habbohotel/items/interactions/wired/effects/WiredEffectJoinTeam.java"),
        new("wf_act_kick_user", WiredBoxCategory.Action, 19, "habbohotel/items/interactions/wired/effects/WiredEffectKickHabbo.java"),
        new("wf_act_leave_team", WiredBoxCategory.Action, 10, "habbohotel/items/interactions/wired/effects/WiredEffectLeaveTeam.java"),
        new("wf_act_log", WiredBoxCategory.Action, 49, "habbohotel/items/interactions/wired/effects/WiredEffectLog.java"),
        new("wf_act_match_to_sshot", WiredBoxCategory.Action, 3, "habbohotel/items/interactions/wired/effects/WiredEffectMatchFurni.java"),
        new("wf_act_move_furni_as_group", WiredBoxCategory.Action, 57, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniAsGroup.java"),
        new("wf_act_move_furni_to", WiredBoxCategory.Action, 16, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniTo.java"),
        new("wf_act_move_rotate", WiredBoxCategory.Action, 4, "habbohotel/items/interactions/wired/effects/WiredEffectMoveRotateFurni.java"),
        new("wf_act_move_rotate_user", WiredBoxCategory.Action, 42, "habbohotel/items/interactions/wired/effects/WiredEffectMoveRotateUser.java"),
        new("wf_act_move_to_dir", WiredBoxCategory.Action, 13, "habbohotel/items/interactions/wired/effects/WiredEffectChangeFurniDirection.java"),
        new("wf_act_mute_triggerer", WiredBoxCategory.Action, 20, "habbohotel/items/interactions/wired/effects/WiredEffectMuteHabbo.java"),
        new("wf_act_neg_call_stacks", WiredBoxCategory.Action, 36, "habbohotel/items/interactions/wired/effects/WiredEffectNegativeTriggerStacks.java"),
        new("wf_act_neg_log", WiredBoxCategory.Action, 50, "habbohotel/items/interactions/wired/effects/WiredEffectNegativeLog.java"),
        new("wf_act_neg_send_signal", WiredBoxCategory.Action, 37, "habbohotel/items/interactions/wired/effects/WiredEffectNegativeSendSignal.java"),
        new("wf_act_place_furni", WiredBoxCategory.Action, 55, "habbohotel/items/interactions/wired/effects/WiredEffectPlaceFurni.java"),
        new("wf_act_rel_mov", WiredBoxCategory.Action, 33, "habbohotel/items/interactions/wired/effects/WiredEffectRelativeMove.java"),
        new("wf_act_remove_furni", WiredBoxCategory.Action, 56, "habbohotel/items/interactions/wired/effects/WiredEffectRemoveFurni.java"),
        new("wf_act_remove_var", WiredBoxCategory.Action, 40, "habbohotel/items/interactions/wired/effects/WiredEffectRemoveVariable.java"),
        new("wf_act_reset_timers", WiredBoxCategory.Action, 1, "habbohotel/items/interactions/wired/effects/WiredEffectResetTimers.java"),
        new("wf_act_send_signal", WiredBoxCategory.Action, 30, "habbohotel/items/interactions/wired/effects/WiredEffectSendSignal.java"),
        new("wf_act_set_altitude", WiredBoxCategory.Action, 29, "habbohotel/items/interactions/wired/effects/WiredEffectSetAltitude.java"),
        new("wf_act_show_message", WiredBoxCategory.Action, 7, "habbohotel/items/interactions/wired/effects/WiredEffectWhisper.java"),
        new("wf_act_teleport_to", WiredBoxCategory.Action, 8, "habbohotel/items/interactions/wired/effects/WiredEffectTeleport.java"),
        new("wf_act_teleport_to_room", WiredBoxCategory.Action, 44, "habbohotel/items/interactions/wired/effects/WiredEffectForwardUserToRoom.java"),
        new("wf_act_toggle_state", WiredBoxCategory.Action, 0, "habbohotel/items/interactions/wired/effects/WiredEffectToggleFurni.java"),
        new("wf_act_toggle_to_rnd", WiredBoxCategory.Action, 15, "habbohotel/items/interactions/wired/effects/WiredEffectToggleRandom.java"),
        new("wf_act_unfreeze", WiredBoxCategory.Action, 32, "habbohotel/items/interactions/wired/effects/WiredEffectUnfreeze.java"),
        new("wf_act_user_to_furni", WiredBoxCategory.Action, 43, "habbohotel/items/interactions/wired/effects/WiredEffectUserToFurni.java"),
        new("wf_cnd_actor_dir", WiredBoxCategory.Condition, 37, "habbohotel/items/interactions/wired/conditions/WiredConditionActorDir.java"),
        new("wf_cnd_actor_in_group", WiredBoxCategory.Condition, 10, "habbohotel/items/interactions/wired/conditions/WiredConditionGroupMember.java"),
        new("wf_cnd_actor_in_team", WiredBoxCategory.Condition, 6, "habbohotel/items/interactions/wired/conditions/WiredConditionTeamMember.java"),
        new("wf_cnd_counter_time_matches", WiredBoxCategory.Condition, 35, "habbohotel/items/interactions/wired/conditions/WiredConditionCounterTimeMatches.java"),
        new("wf_cnd_date_rng_active", WiredBoxCategory.Condition, 24, "habbohotel/items/interactions/wired/conditions/WiredConditionDateRangeActive.java"),
        new("wf_cnd_furnis_hv_avtrs", WiredBoxCategory.Condition, 1, "habbohotel/items/interactions/wired/conditions/WiredConditionFurniHaveHabbo.java"),
        new("wf_cnd_has_altitude", WiredBoxCategory.Condition, 36, "habbohotel/items/interactions/wired/conditions/WiredConditionHasAltitude.java"),
        new("wf_cnd_has_furni_on", WiredBoxCategory.Condition, 7, "habbohotel/items/interactions/wired/conditions/WiredConditionFurniHaveFurni.java"),
        new("wf_cnd_has_handitem", WiredBoxCategory.Condition, 25, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboHasHandItem.java"),
        new("wf_cnd_has_var", WiredBoxCategory.Condition, 40, "habbohotel/items/interactions/wired/conditions/WiredConditionHasVariable.java"),
        new("wf_cnd_match_date", WiredBoxCategory.Condition, 29, "habbohotel/items/interactions/wired/conditions/WiredConditionMatchDate.java"),
        new("wf_cnd_match_snapshot", WiredBoxCategory.Condition, 0, "habbohotel/items/interactions/wired/conditions/WiredConditionMatchStatePosition.java"),
        new("wf_cnd_match_time", WiredBoxCategory.Condition, 28, "habbohotel/items/interactions/wired/conditions/WiredConditionMatchTime.java"),
        new("wf_cnd_neg_has_var", WiredBoxCategory.Condition, 41, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHasVariable.java"),
        new("wf_cnd_not_furni_on", WiredBoxCategory.Condition, 18, "habbohotel/items/interactions/wired/conditions/WiredConditionNotFurniHaveFurni.java"),
        new("wf_cnd_not_has_handitem", WiredBoxCategory.Condition, 30, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboHasHandItem.java"),
        new("wf_cnd_not_hv_avtrs", WiredBoxCategory.Condition, 14, "habbohotel/items/interactions/wired/conditions/WiredConditionNotFurniHaveHabbo.java"),
        new("wf_cnd_not_in_group", WiredBoxCategory.Condition, 21, "habbohotel/items/interactions/wired/conditions/WiredConditionNotInGroup.java"),
        new("wf_cnd_not_in_team", WiredBoxCategory.Condition, 17, "habbohotel/items/interactions/wired/conditions/WiredConditionNotInTeam.java"),
        new("wf_cnd_not_match_snap", WiredBoxCategory.Condition, 13, "habbohotel/items/interactions/wired/conditions/WiredConditionNotMatchStatePosition.java"),
        new("wf_cnd_not_stuff_is", WiredBoxCategory.Condition, 19, "habbohotel/items/interactions/wired/conditions/WiredConditionNotFurniTypeMatch.java"),
        new("wf_cnd_not_trggrer_on", WiredBoxCategory.Condition, 15, "habbohotel/items/interactions/wired/conditions/WiredConditionNotTriggerOnFurni.java"),
        new("wf_cnd_not_triggerer_match", WiredBoxCategory.Condition, 27, "habbohotel/items/interactions/wired/conditions/WiredConditionNotTriggererMatch.java"),
        new("wf_cnd_not_user_count", WiredBoxCategory.Condition, 16, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboCount.java"),
        new("wf_cnd_not_user_performs_action", WiredBoxCategory.Condition, 33, "habbohotel/items/interactions/wired/conditions/WiredConditionNotUserPerformsAction.java"),
        new("wf_cnd_not_wearing_b", WiredBoxCategory.Condition, 22, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboWearsBadge.java"),
        new("wf_cnd_not_wearing_fx", WiredBoxCategory.Condition, 23, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboHasEffect.java"),
        new("wf_cnd_slc_quantity", WiredBoxCategory.Condition, 38, "habbohotel/items/interactions/wired/conditions/WiredConditionSelectionQuantity.java"),
        new("wf_cnd_stuff_is", WiredBoxCategory.Condition, 8, "habbohotel/items/interactions/wired/conditions/WiredConditionFurniTypeMatch.java"),
        new("wf_cnd_team_has_rank", WiredBoxCategory.Condition, 31, "habbohotel/items/interactions/wired/conditions/WiredConditionTeamHasRank.java"),
        new("wf_cnd_team_has_score", WiredBoxCategory.Condition, 34, "habbohotel/items/interactions/wired/conditions/WiredConditionTeamHasScore.java"),
        new("wf_cnd_time_less_than", WiredBoxCategory.Condition, 4, "habbohotel/items/interactions/wired/conditions/WiredConditionLessTimeElapsed.java"),
        new("wf_cnd_time_more_than", WiredBoxCategory.Condition, 3, "habbohotel/items/interactions/wired/conditions/WiredConditionMoreTimeElapsed.java"),
        new("wf_cnd_trggrer_on_frn", WiredBoxCategory.Condition, 2, "habbohotel/items/interactions/wired/conditions/WiredConditionTriggerOnFurni.java"),
        new("wf_cnd_triggerer_match", WiredBoxCategory.Condition, 26, "habbohotel/items/interactions/wired/conditions/WiredConditionTriggererMatch.java"),
        new("wf_cnd_user_count_in", WiredBoxCategory.Condition, 5, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboCount.java"),
        new("wf_cnd_user_performs_action", WiredBoxCategory.Condition, 32, "habbohotel/items/interactions/wired/conditions/WiredConditionUserPerformsAction.java"),
        new("wf_cnd_valid_moves", WiredBoxCategory.Condition, 39, "habbohotel/items/interactions/wired/conditions/WiredConditionMovementValidation.java"),
        new("wf_cnd_var_age_match", WiredBoxCategory.Condition, 43, "habbohotel/items/interactions/wired/conditions/WiredConditionVariableAgeMatch.java"),
        new("wf_cnd_var_val_match", WiredBoxCategory.Condition, 42, "habbohotel/items/interactions/wired/conditions/WiredConditionVariableValueMatch.java"),
        new("wf_cnd_wearing_badge", WiredBoxCategory.Condition, 11, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboWearsBadge.java"),
        new("wf_cnd_wearing_effect", WiredBoxCategory.Condition, 12, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboHasEffect.java"),
        new("wf_slc_furni_altitude", WiredBoxCategory.Selector, 16, "habbohotel/items/interactions/wired/selector/WiredEffectFurniAltitude.java"),
        new("wf_slc_furni_area", WiredBoxCategory.Selector, 7, "habbohotel/items/interactions/wired/selector/WiredEffectFurniArea.java"),
        new("wf_slc_furni_bytype", WiredBoxCategory.Selector, 0, "habbohotel/items/interactions/wired/selector/WiredEffectFurniByType.java"),
        new("wf_slc_furni_neighborhood", WiredBoxCategory.Selector, 6, "habbohotel/items/interactions/wired/selector/WiredEffectFurniNeighborhood.java"),
        new("wf_slc_furni_onfurni", WiredBoxCategory.Selector, 4, "habbohotel/items/interactions/wired/selector/WiredEffectFurniOnFurni.java"),
        new("wf_slc_furni_picks", WiredBoxCategory.Selector, 1, "habbohotel/items/interactions/wired/selector/WiredEffectFurniPicks.java"),
        new("wf_slc_furni_signal", WiredBoxCategory.Selector, 5, "habbohotel/items/interactions/wired/selector/WiredEffectFurniSignal.java"),
        new("wf_slc_furni_with_var", WiredBoxCategory.Selector, 17, "habbohotel/items/interactions/wired/selector/WiredEffectFurniWithVariable.java"),
        new("wf_slc_remote", WiredBoxCategory.Selector, 19, "habbohotel/items/interactions/wired/selector/WiredEffectRemoteSelector.java"),
        new("wf_slc_users_area", WiredBoxCategory.Selector, 13, "habbohotel/items/interactions/wired/selector/WiredEffectUsersArea.java"),
        new("wf_slc_users_byaction", WiredBoxCategory.Selector, 9, "habbohotel/items/interactions/wired/selector/WiredEffectUsersByAction.java"),
        new("wf_slc_users_byname", WiredBoxCategory.Selector, 11, "habbohotel/items/interactions/wired/selector/WiredEffectUsersByName.java"),
        new("wf_slc_users_bytype", WiredBoxCategory.Selector, 2, "habbohotel/items/interactions/wired/selector/WiredEffectUsersByType.java"),
        new("wf_slc_users_group", WiredBoxCategory.Selector, 15, "habbohotel/items/interactions/wired/selector/WiredEffectUsersGroup.java"),
        new("wf_slc_users_handitem", WiredBoxCategory.Selector, 14, "habbohotel/items/interactions/wired/selector/WiredEffectUsersHandItem.java"),
        new("wf_slc_users_neighborhood", WiredBoxCategory.Selector, 12, "habbohotel/items/interactions/wired/selector/WiredEffectUsersNeighborhood.java"),
        new("wf_slc_users_onfurni", WiredBoxCategory.Selector, 8, "habbohotel/items/interactions/wired/selector/WiredEffectUsersOnFurni.java"),
        new("wf_slc_users_signal", WiredBoxCategory.Selector, 10, "habbohotel/items/interactions/wired/selector/WiredEffectUsersSignal.java"),
        new("wf_slc_users_team", WiredBoxCategory.Selector, 3, "habbohotel/items/interactions/wired/selector/WiredEffectUsersTeam.java"),
        new("wf_slc_users_with_var", WiredBoxCategory.Selector, 18, "habbohotel/items/interactions/wired/selector/WiredEffectUsersWithVariable.java"),
        new("wf_trg_at_given_time", WiredBoxCategory.Trigger, 3, "habbohotel/items/interactions/wired/triggers/WiredTriggerAtSetTime.java"),
        new("wf_trg_at_time_long", WiredBoxCategory.Trigger, 3, "habbohotel/items/interactions/wired/triggers/WiredTriggerAtTimeLong.java"),
        new("wf_trg_bot_reached_avtr", WiredBoxCategory.Trigger, 14, "habbohotel/items/interactions/wired/triggers/WiredTriggerBotReachedHabbo.java"),
        new("wf_trg_bot_reached_stf", WiredBoxCategory.Trigger, 13, "habbohotel/items/interactions/wired/triggers/WiredTriggerBotReachedFurni.java"),
        new("wf_trg_click_furni", WiredBoxCategory.Trigger, 18, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboClicksFurni.java"),
        new("wf_trg_click_tile", WiredBoxCategory.Trigger, 21, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboClicksTile.java"),
        new("wf_trg_click_user", WiredBoxCategory.Trigger, 24, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboClicksUser.java"),
        new("wf_trg_clock_counter", WiredBoxCategory.Trigger, 15, "habbohotel/items/interactions/wired/triggers/WiredTriggerClockCounter.java"),
        new("wf_trg_collision", WiredBoxCategory.Trigger, 11, "habbohotel/items/interactions/wired/triggers/WiredTriggerCollision.java"),
        new("wf_trg_enter_room", WiredBoxCategory.Trigger, 7, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboEntersRoom.java"),
        new("wf_trg_game_ends", WiredBoxCategory.Trigger, 9, "habbohotel/items/interactions/wired/triggers/WiredTriggerGameEnds.java"),
        new("wf_trg_game_starts", WiredBoxCategory.Trigger, 8, "habbohotel/items/interactions/wired/triggers/WiredTriggerGameStarts.java"),
        new("wf_trg_leave_room", WiredBoxCategory.Trigger, 23, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboLeavesRoom.java"),
        new("wf_trg_period_long", WiredBoxCategory.Trigger, 12, "habbohotel/items/interactions/wired/triggers/WiredTriggerRepeaterLong.java"),
        new("wf_trg_period_short", WiredBoxCategory.Trigger, 19, "habbohotel/items/interactions/wired/triggers/WiredTriggerRepeaterShort.java"),
        new("wf_trg_periodically", WiredBoxCategory.Trigger, 6, "habbohotel/items/interactions/wired/triggers/WiredTriggerRepeater.java"),
        new("wf_trg_recv_signal", WiredBoxCategory.Trigger, 17, "habbohotel/items/interactions/wired/triggers/WiredTriggerReceiveSignal.java"),
        new("wf_trg_says_something", WiredBoxCategory.Trigger, 0, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboSaysKeyword.java"),
        new("wf_trg_score_achieved", WiredBoxCategory.Trigger, 10, "habbohotel/items/interactions/wired/triggers/WiredTriggerScoreAchieved.java"),
        new("wf_trg_state_changed", WiredBoxCategory.Trigger, 20, "habbohotel/items/interactions/wired/triggers/WiredTriggerFurniStateUpdated.java"),
        new("wf_trg_stuff_state", WiredBoxCategory.Trigger, 4, "habbohotel/items/interactions/wired/triggers/WiredTriggerFurniStateToggled.java"),
        new("wf_trg_user_performs_action", WiredBoxCategory.Trigger, 16, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboPerformsAction.java"),
        new("wf_trg_var_changed", WiredBoxCategory.Trigger, 22, "habbohotel/items/interactions/wired/triggers/WiredTriggerVariableChanged.java"),
        new("wf_trg_walks_off_furni", WiredBoxCategory.Trigger, 2, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboWalkOffFurni.java"),
        new("wf_trg_walks_on_furni", WiredBoxCategory.Trigger, 1, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboWalkOnFurni.java"),
        new("wf_var_context", WiredBoxCategory.Variable, 3, "habbohotel/items/interactions/wired/extra/WiredExtraContextVariable.java"),
        new("wf_var_echo", WiredBoxCategory.Variable, 7, "habbohotel/items/interactions/wired/extra/WiredExtraVariableEcho.java"),
        new("wf_var_furni", WiredBoxCategory.Variable, 0, "habbohotel/items/interactions/wired/extra/WiredExtraFurniVariable.java"),
        new("wf_var_quest", WiredBoxCategory.Variable, 5, "habbohotel/items/interactions/wired/extra/WiredExtraQuest.java"),
        new("wf_var_quest_chain", WiredBoxCategory.Variable, 6, "habbohotel/items/interactions/wired/extra/WiredExtraQuestChain.java"),
        new("wf_var_reference", WiredBoxCategory.Variable, 4, "habbohotel/items/interactions/wired/extra/WiredExtraVariableReference.java"),
        new("wf_var_room", WiredBoxCategory.Variable, 2, "habbohotel/items/interactions/wired/extra/WiredExtraRoomVariable.java"),
        new("wf_var_user", WiredBoxCategory.Variable, 1, "habbohotel/items/interactions/wired/extra/WiredExtraUserVariable.java"),
        new("wf_xtra_anim_time", WiredBoxCategory.Addon, 9, "habbohotel/items/interactions/wired/extra/WiredExtraAnimationTime.java"),
        new("wf_xtra_exec_in_order", WiredBoxCategory.Addon, 17, "habbohotel/items/interactions/wired/extra/WiredExtraExecuteInOrder.java"),
        new("wf_xtra_execution_limit", WiredBoxCategory.Addon, 5, "habbohotel/items/interactions/wired/extra/WiredExtraExecutionLimit.java"),
        new("wf_xtra_filter_furni", WiredBoxCategory.Addon, 10, "habbohotel/items/interactions/wired/extra/WiredExtraFilterFurni.java"),
        new("wf_xtra_filter_furni_by_var", WiredBoxCategory.Addon, 12, "habbohotel/items/interactions/wired/extra/WiredExtraFilterFurniByVariable.java"),
        new("wf_xtra_filter_users", WiredBoxCategory.Addon, 11, "habbohotel/items/interactions/wired/extra/WiredExtraFilterUser.java"),
        new("wf_xtra_filter_users_by_var", WiredBoxCategory.Addon, 13, "habbohotel/items/interactions/wired/extra/WiredExtraFilterUsersByVariable.java"),
        new("wf_xtra_mov_carry_users", WiredBoxCategory.Addon, 8, "habbohotel/items/interactions/wired/extra/WiredExtraMoveCarryUsers.java"),
        new("wf_xtra_mov_curve", WiredBoxCategory.Addon, 22, "habbohotel/items/interactions/wired/extra/WiredExtraMovementCurve.java"),
        new("wf_xtra_mov_no_animation", WiredBoxCategory.Addon, 6, "habbohotel/items/interactions/wired/extra/WiredExtraMoveNoAnimation.java"),
        new("wf_xtra_mov_physics", WiredBoxCategory.Addon, 7, "habbohotel/items/interactions/wired/extra/WiredExtraMovePhysics.java"),
        new("wf_xtra_or_eval", WiredBoxCategory.Addon, 0, "habbohotel/items/interactions/wired/extra/WiredExtraOrEval.java"),
        new("wf_xtra_random", WiredBoxCategory.Addon, 1, "habbohotel/items/interactions/wired/extra/WiredExtraRandom.java"),
        new("wf_xtra_rotate_to_dir", WiredBoxCategory.Addon, 21, "habbohotel/items/interactions/wired/extra/WiredExtraProjectile.java"),
        new("wf_xtra_text_input_variable", WiredBoxCategory.Addon, 16, "habbohotel/items/interactions/wired/extra/WiredExtraTextInputVariable.java"),
        new("wf_xtra_text_output_furni_name", WiredBoxCategory.Addon, 19, "habbohotel/items/interactions/wired/extra/WiredExtraTextOutputFurniName.java"),
        new("wf_xtra_text_output_username", WiredBoxCategory.Addon, 14, "habbohotel/items/interactions/wired/extra/WiredExtraTextOutputUsername.java"),
        new("wf_xtra_text_output_variable", WiredBoxCategory.Addon, 15, "habbohotel/items/interactions/wired/extra/WiredExtraTextOutputVariable.java"),
        new("wf_xtra_unseen", WiredBoxCategory.Addon, 2, "habbohotel/items/interactions/wired/extra/WiredExtraUnseen.java"),
        new("wf_xtra_var_fx_boss", WiredBoxCategory.Addon, 1204, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxBossBar.java"),
        new("wf_xtra_var_fx_health", WiredBoxCategory.Addon, 1200, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxHealthPoints.java"),
        new("wf_xtra_var_fx_level", WiredBoxCategory.Addon, 1202, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxLevellingProgress.java"),
        new("wf_xtra_var_fx_number", WiredBoxCategory.Addon, 1205, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxNumberDisplay.java"),
        new("wf_xtra_var_fx_progress", WiredBoxCategory.Addon, 1201, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxProgressBar.java"),
        new("wf_xtra_var_fx_status", WiredBoxCategory.Addon, 1203, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxStatusBar.java"),
        new("wf_xtra_var_lvlup_system", WiredBoxCategory.Addon, 1001, "habbohotel/items/interactions/wired/extra/WiredExtraVariableLevelUpSystem.java"),
        new("wf_xtra_var_text_connector", WiredBoxCategory.Addon, 1000, "habbohotel/items/interactions/wired/extra/WiredExtraVariableTextConnector.java"),
        new("wf_xtra_var_time_util", WiredBoxCategory.Addon, 1002, "habbohotel/items/interactions/wired/extra/WiredExtraTimeUtilities.java"),
    }.ToFrozenDictionary(descriptor => descriptor.CanonicalName, StringComparer.OrdinalIgnoreCase);

    public static IReadOnlyCollection<WiredBoxDescriptor> All => Descriptors.Values;

    public static bool TryGet(string? name, out WiredBoxDescriptor descriptor)
    {
        descriptor = null!;

        return name != null && Descriptors.TryGetValue(name, out descriptor!);
    }

    /// <summary>The registry descriptor for furniture whose definition names only a legacy wired type.</summary>
    public static bool TryGetByLegacyType(WiredBoxType type, out WiredBoxDescriptor descriptor)
    {
        var name = type switch
        {
            WiredBoxType.TriggerRoomEnter => "wf_trg_enter_room",
            WiredBoxType.TriggerUserSays or WiredBoxType.TriggerUserSaysCommand => "wf_trg_says_something",
            WiredBoxType.TriggerRepeat => "wf_trg_periodically",
            WiredBoxType.TriggerStateChanges => "wf_trg_stuff_state",
            WiredBoxType.TriggerWalkOnFurni => "wf_trg_walks_on_furni",
            WiredBoxType.TriggerWalkOffFurni => "wf_trg_walks_off_furni",
            WiredBoxType.TriggerGameStarts => "wf_trg_game_starts",
            WiredBoxType.TriggerGameEnds => "wf_trg_game_ends",
            WiredBoxType.TriggerUserFurniCollision => "wf_trg_collision",
            WiredBoxType.EffectShowMessage => "wf_act_show_message",
            WiredBoxType.EffectTeleportToFurni => "wf_act_teleport_to",
            WiredBoxType.EffectToggleFurniState => "wf_act_toggle_state",
            WiredBoxType.EffectKickUser => "wf_act_kick_user",
            WiredBoxType.EffectMatchPosition => "wf_act_match_to_sshot",
            WiredBoxType.EffectMoveAndRotate => "wf_act_move_rotate",
            WiredBoxType.EffectMoveFurniToNearestUser => "wf_act_chase",
            WiredBoxType.EffectMoveFurniFromNearestUser => "wf_act_flee",
            WiredBoxType.EffectMuteTriggerer => "wf_act_mute_triggerer",
            WiredBoxType.EffectGiveReward => "wf_act_give_reward",
            WiredBoxType.EffectExecuteWiredStacks => "wf_act_call_stacks",
            WiredBoxType.EffectTeleportBotToFurniBox => "wf_act_bot_teleport",
            WiredBoxType.EffectBotChangesClothesBox => "wf_act_bot_clothes",
            WiredBoxType.EffectBotMovesToFurniBox => "wf_act_bot_move",
            WiredBoxType.EffectBotCommunicatesToAllBox => "wf_act_bot_talk",
            WiredBoxType.EffectBotCommunicatesToUserBox => "wf_act_bot_talk_to_avatar",
            WiredBoxType.EffectBotFollowsUserBox => "wf_act_bot_follow_avatar",
            WiredBoxType.EffectBotGivesHanditemBox => "wf_act_bot_give_handitem",
            WiredBoxType.EffectAddActorToTeam => "wf_act_join_team",
            WiredBoxType.EffectRemoveActorFromTeam => "wf_act_leave_team",
            WiredBoxType.ConditionFurniHasUsers => "wf_cnd_furnis_hv_avtrs",
            WiredBoxType.ConditionFurniHasFurni => "wf_cnd_has_furni_on",
            WiredBoxType.ConditionTriggererOnFurni => "wf_cnd_trggrer_on_frn",
            WiredBoxType.ConditionIsGroupMember => "wf_cnd_actor_in_group",
            WiredBoxType.ConditionIsNotGroupMember => "wf_cnd_not_in_group",
            WiredBoxType.ConditionTriggererNotOnFurni => "wf_cnd_not_trggrer_on",
            WiredBoxType.ConditionFurniHasNoUsers => "wf_cnd_not_hv_avtrs",
            WiredBoxType.ConditionIsWearingBadge => "wf_cnd_wearing_badge",
            WiredBoxType.ConditionIsWearingFx => "wf_cnd_wearing_effect",
            WiredBoxType.ConditionIsNotWearingBadge => "wf_cnd_not_wearing_b",
            WiredBoxType.ConditionIsNotWearingFx => "wf_cnd_not_wearing_fx",
            WiredBoxType.ConditionMatchStateAndPosition => "wf_cnd_match_snapshot",
            WiredBoxType.ConditionDontMatchStateAndPosition => "wf_cnd_not_match_snap",
            WiredBoxType.ConditionUserCountInRoom => "wf_cnd_user_count_in",
            WiredBoxType.ConditionUserCountDoesntInRoom => "wf_cnd_not_user_count",
            WiredBoxType.ConditionFurniHasNoFurni => "wf_cnd_not_furni_on",
            WiredBoxType.ConditionActorHasHandItemBox => "wf_cnd_has_handitem",
            WiredBoxType.ConditionActorIsInTeamBox => "wf_cnd_actor_in_team",
            WiredBoxType.AddonRandomEffect => "wf_xtra_random",
            _ => null
        };

        return WiredBoxRegistry.TryGet(name, out descriptor);
    }
}
