using System.Collections.Frozen;

namespace Plus.HabboHotel.Items.Wired.Configuration;

/// <summary>
/// Protocol facts audited against Turbo d5a54747 and Polaris 34bc0d49; behavioral registration
/// remains the concrete factory's responsibility. Octane uses three legacy envelopes for six kinds.
/// </summary>
public static class WiredBoxRegistry
{
    private static readonly FrozenDictionary<string, WiredBoxDescriptor> Descriptors = new WiredBoxDescriptor[]
    {
        new("wf_act_adjust_clock", WiredBoxCategory.Action, 42, 38, "habbohotel/items/interactions/wired/effects/WiredEffectAdjustClock.java"),
        new("wf_act_bot_clothes", WiredBoxCategory.Action, 26, 26, "habbohotel/items/interactions/wired/effects/WiredEffectBotClothes.java"),
        new("wf_act_bot_follow_avatar", WiredBoxCategory.Action, 25, 25, "habbohotel/items/interactions/wired/effects/WiredEffectBotFollowHabbo.java"),
        new("wf_act_bot_give_handitem", WiredBoxCategory.Action, 24, 24, "habbohotel/items/interactions/wired/effects/WiredEffectBotGiveHandItem.java"),
        new("wf_act_bot_move", WiredBoxCategory.Action, 22, 22, "habbohotel/items/interactions/wired/effects/WiredEffectBotWalkToFurni.java"),
        new("wf_act_bot_talk", WiredBoxCategory.Action, 23, 23, "habbohotel/items/interactions/wired/effects/WiredEffectBotTalk.java"),
        new("wf_act_bot_talk_to_avatar", WiredBoxCategory.Action, 27, 27, "habbohotel/items/interactions/wired/effects/WiredEffectBotTalkToHabbo.java"),
        new("wf_act_bot_teleport", WiredBoxCategory.Action, 21, 21, "habbohotel/items/interactions/wired/effects/WiredEffectBotTeleport.java"),
        new("wf_act_call_stacks", WiredBoxCategory.Action, 18, 18, "habbohotel/items/interactions/wired/effects/WiredEffectTriggerStacks.java"),
        new("wf_act_change_var_val", WiredBoxCategory.Action, 74, 41, "habbohotel/items/interactions/wired/effects/WiredEffectChangeVariableValue.java"),
        new("wf_act_chase", WiredBoxCategory.Action, 11, 11, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniTowards.java"),
        new("wf_act_click_conf", WiredBoxCategory.Action, 129, 54, "habbohotel/items/interactions/wired/effects/WiredEffectClickSettings.java"),
        new("wf_act_control_clock", WiredBoxCategory.Action, 41, 28, "habbohotel/items/interactions/wired/effects/WiredEffectControlClock.java"),
        new("wf_act_flee", WiredBoxCategory.Action, 12, 12, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniAway.java"),
        new("wf_act_freeze", WiredBoxCategory.Action, 34, 31, "habbohotel/items/interactions/wired/effects/WiredEffectFreeze.java"),
        new("wf_act_furni_to_furni", WiredBoxCategory.Action, 38, 34, "habbohotel/items/interactions/wired/effects/WiredEffectFurniToFurni.java"),
        new("wf_act_furni_to_user", WiredBoxCategory.Action, 36, 35, "habbohotel/items/interactions/wired/effects/WiredEffectFurniToUser.java"),
        new("wf_act_give_reward", WiredBoxCategory.Action, 17, 17, "habbohotel/items/interactions/wired/effects/WiredEffectGiveReward.java"),
        new("wf_act_give_score", WiredBoxCategory.Action, 6, 6, "habbohotel/items/interactions/wired/effects/WiredEffectGiveScore.java"),
        new("wf_act_give_score_tm", WiredBoxCategory.Action, 14, 14, "habbohotel/items/interactions/wired/effects/WiredEffectGiveScoreToTeam.java"),
        new("wf_act_give_var", WiredBoxCategory.Action, 69, 39, "habbohotel/items/interactions/wired/effects/WiredEffectGiveVariable.java"),
        new("wf_act_join_team", WiredBoxCategory.Action, 9, 9, "habbohotel/items/interactions/wired/effects/WiredEffectJoinTeam.java"),
        new("wf_act_kick_user", WiredBoxCategory.Action, 19, 19, "habbohotel/items/interactions/wired/effects/WiredEffectKickHabbo.java"),
        new("wf_act_leave_team", WiredBoxCategory.Action, 10, 10, "habbohotel/items/interactions/wired/effects/WiredEffectLeaveTeam.java"),
        new("wf_act_log", WiredBoxCategory.Action, 137, 49, "habbohotel/items/interactions/wired/effects/WiredEffectLog.java"),
        new("wf_act_match_to_sshot", WiredBoxCategory.Action, 3, 3, "habbohotel/items/interactions/wired/effects/WiredEffectMatchFurni.java"),
        new("wf_act_move_furni_as_group", WiredBoxCategory.Action, 95, 57, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniAsGroup.java"),
        new("wf_act_move_furni_to", WiredBoxCategory.Action, 16, 16, "habbohotel/items/interactions/wired/effects/WiredEffectMoveFurniTo.java"),
        new("wf_act_move_rotate", WiredBoxCategory.Action, 4, 4, "habbohotel/items/interactions/wired/effects/WiredEffectMoveRotateFurni.java"),
        new("wf_act_move_rotate_user", WiredBoxCategory.Action, 43, 42, "habbohotel/items/interactions/wired/effects/WiredEffectMoveRotateUser.java"),
        new("wf_act_move_to_dir", WiredBoxCategory.Action, 13, 13, "habbohotel/items/interactions/wired/effects/WiredEffectChangeFurniDirection.java"),
        new("wf_act_mute_triggerer", WiredBoxCategory.Action, 20, 20, "habbohotel/items/interactions/wired/effects/WiredEffectMuteHabbo.java"),
        new("wf_act_neg_call_stacks", WiredBoxCategory.Action, 86, 36, "habbohotel/items/interactions/wired/effects/WiredEffectNegativeTriggerStacks.java"),
        new("wf_act_neg_log", WiredBoxCategory.Action, 137, 50, "habbohotel/items/interactions/wired/effects/WiredEffectNegativeLog.java"),
        new("wf_act_neg_send_signal", WiredBoxCategory.Action, 87, 37, "habbohotel/items/interactions/wired/effects/WiredEffectNegativeSendSignal.java"),
        new("wf_act_place_furni", WiredBoxCategory.Action, 106, 55, "habbohotel/items/interactions/wired/effects/WiredEffectPlaceFurni.java"),
        new("wf_act_rel_mov", WiredBoxCategory.Action, 40, 33, "habbohotel/items/interactions/wired/effects/WiredEffectRelativeMove.java"),
        new("wf_act_remove_furni", WiredBoxCategory.Action, 107, 56, "habbohotel/items/interactions/wired/effects/WiredEffectRemoveFurni.java"),
        new("wf_act_remove_var", WiredBoxCategory.Action, 73, 40, "habbohotel/items/interactions/wired/effects/WiredEffectRemoveVariable.java"),
        new("wf_act_reset_timers", WiredBoxCategory.Action, 1, 1, "habbohotel/items/interactions/wired/effects/WiredEffectResetTimers.java"),
        new("wf_act_send_signal", WiredBoxCategory.Action, 33, 30, "habbohotel/items/interactions/wired/effects/WiredEffectSendSignal.java"),
        new("wf_act_set_altitude", WiredBoxCategory.Action, 39, 29, "habbohotel/items/interactions/wired/effects/WiredEffectSetAltitude.java"),
        new("wf_act_show_message", WiredBoxCategory.Action, 7, 7, "habbohotel/items/interactions/wired/effects/WiredEffectWhisper.java"),
        new("wf_act_teleport_to", WiredBoxCategory.Action, 8, 8, "habbohotel/items/interactions/wired/effects/WiredEffectTeleport.java"),
        new("wf_act_teleport_to_room", WiredBoxCategory.Action, 138, 44, "habbohotel/items/interactions/wired/effects/WiredEffectForwardUserToRoom.java"),
        new("wf_act_toggle_state", WiredBoxCategory.Action, 0, 0, "habbohotel/items/interactions/wired/effects/WiredEffectToggleFurni.java"),
        new("wf_act_toggle_to_rnd", WiredBoxCategory.Action, 15, 15, "habbohotel/items/interactions/wired/effects/WiredEffectToggleRandom.java"),
        new("wf_act_unfreeze", WiredBoxCategory.Action, 35, 32, "habbohotel/items/interactions/wired/effects/WiredEffectUnfreeze.java"),
        new("wf_act_user_to_furni", WiredBoxCategory.Action, 37, 43, "habbohotel/items/interactions/wired/effects/WiredEffectUserToFurni.java"),
        new("wf_cnd_actor_dir", WiredBoxCategory.Condition, 38, 37, "habbohotel/items/interactions/wired/conditions/WiredConditionActorDir.java"),
        new("wf_cnd_actor_in_group", WiredBoxCategory.Condition, 10, 10, "habbohotel/items/interactions/wired/conditions/WiredConditionGroupMember.java"),
        new("wf_cnd_actor_in_team", WiredBoxCategory.Condition, 6, 6, "habbohotel/items/interactions/wired/conditions/WiredConditionTeamMember.java"),
        new("wf_cnd_counter_time_matches", WiredBoxCategory.Condition, 27, 35, "habbohotel/items/interactions/wired/conditions/WiredConditionCounterTimeMatches.java"),
        new("wf_cnd_date_rng_active", WiredBoxCategory.Condition, 24, 24, "habbohotel/items/interactions/wired/conditions/WiredConditionDateRangeActive.java"),
        new("wf_cnd_furnis_hv_avtrs", WiredBoxCategory.Condition, 1, 1, "habbohotel/items/interactions/wired/conditions/WiredConditionFurniHaveHabbo.java"),
        new("wf_cnd_has_altitude", WiredBoxCategory.Condition, 29, 36, "habbohotel/items/interactions/wired/conditions/WiredConditionHasAltitude.java"),
        new("wf_cnd_has_furni_on", WiredBoxCategory.Condition, 7, 7, "habbohotel/items/interactions/wired/conditions/WiredConditionFurniHaveFurni.java"),
        new("wf_cnd_has_handitem", WiredBoxCategory.Condition, 25, 25, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboHasHandItem.java"),
        new("wf_cnd_has_var", WiredBoxCategory.Condition, 40, 40, "habbohotel/items/interactions/wired/conditions/WiredConditionHasVariable.java"),
        new("wf_cnd_match_date", WiredBoxCategory.Condition, 37, 29, "habbohotel/items/interactions/wired/conditions/WiredConditionMatchDate.java"),
        new("wf_cnd_match_snapshot", WiredBoxCategory.Condition, 0, 0, "habbohotel/items/interactions/wired/conditions/WiredConditionMatchStatePosition.java"),
        new("wf_cnd_match_time", WiredBoxCategory.Condition, 36, 28, "habbohotel/items/interactions/wired/conditions/WiredConditionMatchTime.java"),
        new("wf_cnd_neg_has_var", WiredBoxCategory.Condition, 41, 41, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHasVariable.java"),
        new("wf_cnd_not_furni_on", WiredBoxCategory.Condition, 18, 18, "habbohotel/items/interactions/wired/conditions/WiredConditionNotFurniHaveFurni.java"),
        new("wf_cnd_not_has_handitem", WiredBoxCategory.Condition, 31, 30, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboHasHandItem.java"),
        new("wf_cnd_not_hv_avtrs", WiredBoxCategory.Condition, 14, 14, "habbohotel/items/interactions/wired/conditions/WiredConditionNotFurniHaveHabbo.java"),
        new("wf_cnd_not_in_group", WiredBoxCategory.Condition, 21, 21, "habbohotel/items/interactions/wired/conditions/WiredConditionNotInGroup.java"),
        new("wf_cnd_not_in_team", WiredBoxCategory.Condition, 17, 17, "habbohotel/items/interactions/wired/conditions/WiredConditionNotInTeam.java"),
        new("wf_cnd_not_match_snap", WiredBoxCategory.Condition, 13, 13, "habbohotel/items/interactions/wired/conditions/WiredConditionNotMatchStatePosition.java"),
        new("wf_cnd_not_stuff_is", WiredBoxCategory.Condition, 19, 19, "habbohotel/items/interactions/wired/conditions/WiredConditionNotFurniTypeMatch.java"),
        new("wf_cnd_not_trggrer_on", WiredBoxCategory.Condition, 15, 15, "habbohotel/items/interactions/wired/conditions/WiredConditionNotTriggerOnFurni.java"),
        new("wf_cnd_not_triggerer_match", WiredBoxCategory.Condition, 33, 27, "habbohotel/items/interactions/wired/conditions/WiredConditionNotTriggererMatch.java"),
        new("wf_cnd_not_user_count", WiredBoxCategory.Condition, 16, 16, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboCount.java"),
        new("wf_cnd_not_user_performs_action", WiredBoxCategory.Condition, 30, 33, "habbohotel/items/interactions/wired/conditions/WiredConditionNotUserPerformsAction.java"),
        new("wf_cnd_not_wearing_b", WiredBoxCategory.Condition, 22, 22, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboWearsBadge.java"),
        new("wf_cnd_not_wearing_fx", WiredBoxCategory.Condition, 23, 23, "habbohotel/items/interactions/wired/conditions/WiredConditionNotHabboHasEffect.java"),
        new("wf_cnd_slc_quantity", WiredBoxCategory.Condition, 39, 38, "habbohotel/items/interactions/wired/conditions/WiredConditionSelectionQuantity.java"),
        new("wf_cnd_stuff_is", WiredBoxCategory.Condition, 8, 8, "habbohotel/items/interactions/wired/conditions/WiredConditionFurniTypeMatch.java"),
        new("wf_cnd_team_has_rank", WiredBoxCategory.Condition, 35, 31, "habbohotel/items/interactions/wired/conditions/WiredConditionTeamHasRank.java"),
        new("wf_cnd_team_has_score", WiredBoxCategory.Condition, 34, 34, "habbohotel/items/interactions/wired/conditions/WiredConditionTeamHasScore.java"),
        new("wf_cnd_time_less_than", WiredBoxCategory.Condition, 4, 4, "habbohotel/items/interactions/wired/conditions/WiredConditionLessTimeElapsed.java"),
        new("wf_cnd_time_more_than", WiredBoxCategory.Condition, 3, 3, "habbohotel/items/interactions/wired/conditions/WiredConditionMoreTimeElapsed.java"),
        new("wf_cnd_trggrer_on_frn", WiredBoxCategory.Condition, 2, 2, "habbohotel/items/interactions/wired/conditions/WiredConditionTriggerOnFurni.java"),
        new("wf_cnd_triggerer_match", WiredBoxCategory.Condition, 32, 26, "habbohotel/items/interactions/wired/conditions/WiredConditionTriggererMatch.java"),
        new("wf_cnd_user_count_in", WiredBoxCategory.Condition, 5, 5, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboCount.java"),
        new("wf_cnd_user_performs_action", WiredBoxCategory.Condition, 28, 32, "habbohotel/items/interactions/wired/conditions/WiredConditionUserPerformsAction.java"),
        new("wf_cnd_valid_moves", WiredBoxCategory.Condition, 26, 39, "habbohotel/items/interactions/wired/conditions/WiredConditionMovementValidation.java"),
        new("wf_cnd_var_age_match", WiredBoxCategory.Condition, 43, 43, "habbohotel/items/interactions/wired/conditions/WiredConditionVariableAgeMatch.java"),
        new("wf_cnd_var_val_match", WiredBoxCategory.Condition, 42, 42, "habbohotel/items/interactions/wired/conditions/WiredConditionVariableValueMatch.java"),
        new("wf_cnd_wearing_badge", WiredBoxCategory.Condition, 11, 11, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboWearsBadge.java"),
        new("wf_cnd_wearing_effect", WiredBoxCategory.Condition, 12, 12, "habbohotel/items/interactions/wired/conditions/WiredConditionHabboHasEffect.java"),
        new("wf_slc_furni_altitude", WiredBoxCategory.Selector, 44, 16, "habbohotel/items/interactions/wired/selector/WiredEffectFurniAltitude.java"),
        new("wf_slc_furni_area", WiredBoxCategory.Selector, 28, 7, "habbohotel/items/interactions/wired/selector/WiredEffectFurniArea.java"),
        new("wf_slc_furni_bytype", WiredBoxCategory.Selector, 30, 0, "habbohotel/items/interactions/wired/selector/WiredEffectFurniByType.java"),
        new("wf_slc_furni_neighborhood", WiredBoxCategory.Selector, 29, 6, "habbohotel/items/interactions/wired/selector/WiredEffectFurniNeighborhood.java"),
        new("wf_slc_furni_onfurni", WiredBoxCategory.Selector, 45, 4, "habbohotel/items/interactions/wired/selector/WiredEffectFurniOnFurni.java"),
        new("wf_slc_furni_picks", WiredBoxCategory.Selector, 46, 1, "habbohotel/items/interactions/wired/selector/WiredEffectFurniPicks.java"),
        new("wf_slc_furni_signal", WiredBoxCategory.Selector, 47, 5, "habbohotel/items/interactions/wired/selector/WiredEffectFurniSignal.java"),
        new("wf_slc_furni_with_var", WiredBoxCategory.Selector, 75, 17, "habbohotel/items/interactions/wired/selector/WiredEffectFurniWithVariable.java"),
        new("wf_slc_remote", WiredBoxCategory.Selector, 96, 19, "habbohotel/items/interactions/wired/selector/WiredEffectRemoteSelector.java"),
        new("wf_slc_users_area", WiredBoxCategory.Selector, 31, 13, "habbohotel/items/interactions/wired/selector/WiredEffectUsersArea.java"),
        new("wf_slc_users_byaction", WiredBoxCategory.Selector, 51, 9, "habbohotel/items/interactions/wired/selector/WiredEffectUsersByAction.java"),
        new("wf_slc_users_byname", WiredBoxCategory.Selector, 52, 11, "habbohotel/items/interactions/wired/selector/WiredEffectUsersByName.java"),
        new("wf_slc_users_bytype", WiredBoxCategory.Selector, 49, 2, "habbohotel/items/interactions/wired/selector/WiredEffectUsersByType.java"),
        new("wf_slc_users_group", WiredBoxCategory.Selector, 54, 15, "habbohotel/items/interactions/wired/selector/WiredEffectUsersGroup.java"),
        new("wf_slc_users_handitem", WiredBoxCategory.Selector, 55, 14, "habbohotel/items/interactions/wired/selector/WiredEffectUsersHandItem.java"),
        new("wf_slc_users_neighborhood", WiredBoxCategory.Selector, 32, 12, "habbohotel/items/interactions/wired/selector/WiredEffectUsersNeighborhood.java"),
        new("wf_slc_users_onfurni", WiredBoxCategory.Selector, 53, 8, "habbohotel/items/interactions/wired/selector/WiredEffectUsersOnFurni.java"),
        new("wf_slc_users_signal", WiredBoxCategory.Selector, 48, 10, "habbohotel/items/interactions/wired/selector/WiredEffectUsersSignal.java"),
        new("wf_slc_users_team", WiredBoxCategory.Selector, 50, 3, "habbohotel/items/interactions/wired/selector/WiredEffectUsersTeam.java"),
        new("wf_slc_users_with_var", WiredBoxCategory.Selector, 76, 18, "habbohotel/items/interactions/wired/selector/WiredEffectUsersWithVariable.java"),
        new("wf_trg_at_given_time", WiredBoxCategory.Trigger, 3, 3, "habbohotel/items/interactions/wired/triggers/WiredTriggerAtSetTime.java"),
        new("wf_trg_at_time_long", WiredBoxCategory.Trigger, 30, 12, "habbohotel/items/interactions/wired/triggers/WiredTriggerAtTimeLong.java"),
        new("wf_trg_bot_reached_avtr", WiredBoxCategory.Trigger, 14, 14, "habbohotel/items/interactions/wired/triggers/WiredTriggerBotReachedHabbo.java"),
        new("wf_trg_bot_reached_stf", WiredBoxCategory.Trigger, 13, 13, "habbohotel/items/interactions/wired/triggers/WiredTriggerBotReachedFurni.java"),
        new("wf_trg_click_furni", WiredBoxCategory.Trigger, 18, 18, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboClicksFurni.java"),
        new("wf_trg_click_tile", WiredBoxCategory.Trigger, 19, 21, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboClicksTile.java"),
        new("wf_trg_click_user", WiredBoxCategory.Trigger, 20, 24, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboClicksUser.java"),
        new("wf_trg_clock_counter", WiredBoxCategory.Trigger, 22, 15, "habbohotel/items/interactions/wired/triggers/WiredTriggerClockCounter.java"),
        new("wf_trg_collision", WiredBoxCategory.Trigger, 11, 11, "habbohotel/items/interactions/wired/triggers/WiredTriggerCollision.java"),
        new("wf_trg_enter_room", WiredBoxCategory.Trigger, 7, 7, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboEntersRoom.java"),
        new("wf_trg_game_ends", WiredBoxCategory.Trigger, 9, 9, "habbohotel/items/interactions/wired/triggers/WiredTriggerGameEnds.java"),
        new("wf_trg_game_starts", WiredBoxCategory.Trigger, 8, 8, "habbohotel/items/interactions/wired/triggers/WiredTriggerGameStarts.java"),
        new("wf_trg_leave_room", WiredBoxCategory.Trigger, 16, 23, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboLeavesRoom.java"),
        new("wf_trg_period_long", WiredBoxCategory.Trigger, 12, 12, "habbohotel/items/interactions/wired/triggers/WiredTriggerRepeaterLong.java"),
        new("wf_trg_period_short", WiredBoxCategory.Trigger, 17, 19, "habbohotel/items/interactions/wired/triggers/WiredTriggerRepeaterShort.java"),
        new("wf_trg_periodically", WiredBoxCategory.Trigger, 6, 6, "habbohotel/items/interactions/wired/triggers/WiredTriggerRepeater.java"),
        new("wf_trg_recv_signal", WiredBoxCategory.Trigger, 15, 17, "habbohotel/items/interactions/wired/triggers/WiredTriggerReceiveSignal.java"),
        new("wf_trg_says_something", WiredBoxCategory.Trigger, 0, 0, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboSaysKeyword.java"),
        new("wf_trg_score_achieved", WiredBoxCategory.Trigger, 10, 10, "habbohotel/items/interactions/wired/triggers/WiredTriggerScoreAchieved.java"),
        new("wf_trg_state_changed", WiredBoxCategory.Trigger, 32, 20, "habbohotel/items/interactions/wired/triggers/WiredTriggerFurniStateUpdated.java"),
        new("wf_trg_stuff_state", WiredBoxCategory.Trigger, 4, 4, "habbohotel/items/interactions/wired/triggers/WiredTriggerFurniStateToggled.java"),
        new("wf_trg_user_performs_action", WiredBoxCategory.Trigger, 21, 16, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboPerformsAction.java"),
        new("wf_trg_var_changed", WiredBoxCategory.Trigger, 23, 22, "habbohotel/items/interactions/wired/triggers/WiredTriggerVariableChanged.java"),
        new("wf_trg_walks_off_furni", WiredBoxCategory.Trigger, 2, 2, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboWalkOffFurni.java"),
        new("wf_trg_walks_on_furni", WiredBoxCategory.Trigger, 1, 1, "habbohotel/items/interactions/wired/triggers/WiredTriggerHabboWalkOnFurni.java"),
        new("wf_var_context", WiredBoxCategory.Variable, 84, 3, "habbohotel/items/interactions/wired/extra/WiredExtraContextVariable.java"),
        new("wf_var_echo", WiredBoxCategory.Variable, 83, 7, "habbohotel/items/interactions/wired/extra/WiredExtraVariableEcho.java"),
        new("wf_var_furni", WiredBoxCategory.Variable, 71, 0, "habbohotel/items/interactions/wired/extra/WiredExtraFurniVariable.java"),
        new("wf_var_quest", WiredBoxCategory.Variable, 108, 5, "habbohotel/items/interactions/wired/extra/WiredExtraQuest.java"),
        new("wf_var_quest_chain", WiredBoxCategory.Variable, 109, 6, "habbohotel/items/interactions/wired/extra/WiredExtraQuestChain.java"),
        new("wf_var_reference", WiredBoxCategory.Variable, 81, 4, "habbohotel/items/interactions/wired/extra/WiredExtraVariableReference.java"),
        new("wf_var_room", WiredBoxCategory.Variable, 72, 2, "habbohotel/items/interactions/wired/extra/WiredExtraRoomVariable.java"),
        new("wf_var_user", WiredBoxCategory.Variable, 70, 1, "habbohotel/items/interactions/wired/extra/WiredExtraUserVariable.java"),
        new("wf_xtra_anim_time", WiredBoxCategory.Addon, 60, 9, "habbohotel/items/interactions/wired/extra/WiredExtraAnimationTime.java"),
        new("wf_xtra_exec_in_order", WiredBoxCategory.Addon, 64, 17, "habbohotel/items/interactions/wired/extra/WiredExtraExecuteInOrder.java"),
        new("wf_xtra_execution_limit", WiredBoxCategory.Addon, 65, 5, "habbohotel/items/interactions/wired/extra/WiredExtraExecutionLimit.java"),
        new("wf_xtra_filter_furni", WiredBoxCategory.Addon, 56, 10, "habbohotel/items/interactions/wired/extra/WiredExtraFilterFurni.java"),
        new("wf_xtra_filter_furni_by_var", WiredBoxCategory.Addon, 78, 12, "habbohotel/items/interactions/wired/extra/WiredExtraFilterFurniByVariable.java"),
        new("wf_xtra_filter_users", WiredBoxCategory.Addon, 57, 11, "habbohotel/items/interactions/wired/extra/WiredExtraFilterUser.java"),
        new("wf_xtra_filter_users_by_var", WiredBoxCategory.Addon, 77, 13, "habbohotel/items/interactions/wired/extra/WiredExtraFilterUsersByVariable.java"),
        new("wf_xtra_mov_carry_users", WiredBoxCategory.Addon, 58, 8, "habbohotel/items/interactions/wired/extra/WiredExtraMoveCarryUsers.java"),
        new("wf_xtra_mov_curve", WiredBoxCategory.Addon, 97, 22, "habbohotel/items/interactions/wired/extra/WiredExtraMovementCurve.java"),
        new("wf_xtra_mov_no_animation", WiredBoxCategory.Addon, 59, 6, "habbohotel/items/interactions/wired/extra/WiredExtraMoveNoAnimation.java"),
        new("wf_xtra_mov_physics", WiredBoxCategory.Addon, 61, 7, "habbohotel/items/interactions/wired/extra/WiredExtraMovePhysics.java"),
        new("wf_xtra_or_eval", WiredBoxCategory.Addon, 66, 0, "habbohotel/items/interactions/wired/extra/WiredExtraOrEval.java"),
        new("wf_xtra_random", WiredBoxCategory.Addon, 63, 1, "habbohotel/items/interactions/wired/extra/WiredExtraRandom.java"),
        new("wf_xtra_rotate_to_dir", WiredBoxCategory.Addon, 136, 21, "habbohotel/items/interactions/wired/extra/WiredExtraProjectile.java"),
        new("wf_xtra_text_input_variable", WiredBoxCategory.Addon, 85, 16, "habbohotel/items/interactions/wired/extra/WiredExtraTextInputVariable.java"),
        new("wf_xtra_text_output_furni_name", WiredBoxCategory.Addon, 68, 19, "habbohotel/items/interactions/wired/extra/WiredExtraTextOutputFurniName.java"),
        new("wf_xtra_text_output_username", WiredBoxCategory.Addon, 67, 14, "habbohotel/items/interactions/wired/extra/WiredExtraTextOutputUsername.java"),
        new("wf_xtra_text_output_variable", WiredBoxCategory.Addon, 80, 15, "habbohotel/items/interactions/wired/extra/WiredExtraTextOutputVariable.java"),
        new("wf_xtra_unseen", WiredBoxCategory.Addon, 62, 2, "habbohotel/items/interactions/wired/extra/WiredExtraUnseen.java"),
        new("wf_xtra_var_fx_boss", WiredBoxCategory.Addon, 134, 1204, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxBossBar.java"),
        new("wf_xtra_var_fx_health", WiredBoxCategory.Addon, 130, 1200, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxHealthPoints.java"),
        new("wf_xtra_var_fx_level", WiredBoxCategory.Addon, 132, 1202, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxLevellingProgress.java"),
        new("wf_xtra_var_fx_number", WiredBoxCategory.Addon, 135, 1205, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxNumberDisplay.java"),
        new("wf_xtra_var_fx_progress", WiredBoxCategory.Addon, 131, 1201, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxProgressBar.java"),
        new("wf_xtra_var_fx_status", WiredBoxCategory.Addon, 133, 1203, "habbohotel/items/interactions/wired/extra/WiredExtraVariableFxStatusBar.java"),
        new("wf_xtra_var_lvlup_system", WiredBoxCategory.Addon, 82, 1001, "habbohotel/items/interactions/wired/extra/WiredExtraVariableLevelUpSystem.java"),
        new("wf_xtra_var_text_connector", WiredBoxCategory.Addon, 79, 1000, "habbohotel/items/interactions/wired/extra/WiredExtraVariableTextConnector.java"),
        new("wf_xtra_var_time_util", WiredBoxCategory.Addon, 98, 1002, "habbohotel/items/interactions/wired/extra/WiredExtraTimeUtilities.java"),
    }.ToFrozenDictionary(descriptor => descriptor.CanonicalName, StringComparer.OrdinalIgnoreCase);

    public static IReadOnlyCollection<WiredBoxDescriptor> All => Descriptors.Values;

    public static bool TryGet(string? name, out WiredBoxDescriptor descriptor)
    {
        descriptor = null!;
        return name != null && Descriptors.TryGetValue(name, out descriptor!);
    }
}
