ALTER TABLE room_models
    ADD COLUMN IF NOT EXISTS half_scale BOOL NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS camera_x INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS camera_y INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS camera_z FLOAT NOT NULL DEFAULT 0;
